#!/bin/bash

input=$(echo $1 | sed 's/ /+/')

output=$(curl https://1337x.to/search/$input/1/ 2>/dev/null| grep -e coll | tail -n +7)

echo . > leetout

while IFS= read -r line; do
	case "$line" in
		*"name"*)
			magnet=$(echo $line | sed 's/^.*href="//' | sed 's/">.*//')
			magnet=$(curl https://1337x.to$magnet 2>/dev/null | grep 'href="magnet' | sed 's/.*href="//' | sed 's/".*//' | tail -n 1)
			echo $magnet | tee -a leetout
			echo title: $(echo $line | sed 's/.*\/">//' | sed 's/<\/a.*//') | tee -a leetout
			;;
		*"size"*)
			echo size: $(echo $line | sed 's/<span.*//' | sed 's/.*">//') | tee -a leetout
			;;
		*"seeds"*)
			echo seeds: $(echo $line | sed 's/.*seeds">//' | sed 's/<\/td.*//') | tee -a leetout
			;;
		*"leeches"*)
			echo leeches: $(echo $line | sed 's/.*leeches">//' | sed 's/<\/td.*//') | tee -a leetout
			;;
		*"date"*)
			echo date: $(echo $line | sed 's/.*date">//' | sed 's/<\/td.*//') | tee -a leetout
			;;
		*"coll-5"*)
			echo uploader: $(echo $line | sed 's/.*href="//' | sed 's/">.*//') | tee -a leetout
			echo . | tee -a leetout
			;;
		*)
			echo $line | tee -a leetout
			;;
	esac
done <<< "$output"

